---
 - name: Plabook to install docker on ubuntu machine
   hosts: ubuntu2
   become: true
   vars_files:
     vars/default.yml
   tasks:
   
    - name: Installing required system packages
      apt:
       name: "{{ item }}"
       state: latest
       update_cache: true
      with_items:
       - "{{ packages }}"

    - name: Add Docker GPG apt key
      apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present
    
    - name: Add docker Repo
      apt_repository:
       repo: deb https://download.docker.com/linux/ubuntu bionic stable
       state: present

    - name: update cache and install docker-ce
      apt:
       name: docker-ce
       state: latest
       update_cache: true

    - name: installing python module for docker ansible handling
      pip:
       name: docker
   
    - name: Add user avi to docker group
      user:
        name: avi
        groups: docker
        append: yes
   
#    - name: pulling a docker image
#      docker_image:
#        name: "{{ container_image }}"
#        source: pull

#    - name: creating container
#      docker_container:
#       name: "{{ container_name }}{{ item }}"
#       image: "{{ container_image }}"
#       command: "{{ container_command }}"
#      with_sequence: count={{ containers }}
       
